trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- stage: UIE2ETests
  displayName: 'UI E2E Test'
  dependsOn: []
  jobs:
   - template: templates/ui-e2e.yml
